#cloud-config

coreos:
  fleet:
    metadata: role=back
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the intial size of your cluster with ?size=X
    discovery: http://192.168.3.149:8001/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83
    # multi-region and multi-cloud deployments need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      command: restart
      drop-ins:
        - name: docker_opts.conf
          content: |
            [Service]
            Environment="DOCKER_OPTS=--registry-mirror=http://192.168.3.149:5000 --insecure-registry=192.168.3.149"
 
ssh_authorized_keys:
  # include one or more SSH public keys
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAzlyD7ANhZtlqN02IlcSsvqElCGCnxjzpgUJNFiEoICMqKIbQR0UtRHHFq4zqxb35ejDCKFowTeuS0WCqYGbu2ZX19opH3TWuw315mepq+Xyt1x0c/N4qKJyNqrjlaqW0x9SZacyUD4VPO8LiHwqcG0KVB9aFg6xaKLbXK/eyHBRYUoKfNOGecFOGdGr0qplVC4TTetViyUI3vwlD8GOB1F17I40eTHYL/95bbrGzdC5/HBFQfYlOODZHTdbcUzwYTkG9QHPm63b61yiKCHOpkTp3BIvqqOOIpfc4ECHqUd7kw7WNdbWayi00IV+WBSyRWd/CxBda3ODIxVICw3So5Q== root@controller1

write_files:
  - path: /etc/resolv.conf
    permissions: 0644
    owner: root
    content: |
      nameserver 146.11.115.200
      nameserver 146.11.5.10
      nameserver 153.88.112.200
  - path: /etc/systemd/system/update-engine.service.d/proxy.conf
    content: |
      [Service]
      Environment=ALL_PROXY=http://10.175.250.81:8080
  - path: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: core:core
    permissions: 0644
    content: |
      [Service]
      Environment="HTTP_PROXY=http://10.175.250.81:8080" "HTTPS_PROXY=http://10.175.250.81:8080" "NO_PROXY=127.0.0.1,localhost,192.168.3.149,/var/run/docker.sock"


