#!/bin/bash
nova boot \
--user-data ./cloud-config-front2.yaml \
--image 73b99bd1-aecc-473e-a403-d1b2e7df6203  \
--key-name duffqiu \
--flavor m1.medium \
--security-groups default  \
--block-device id=292058fb-2cda-4a83-894c-164e06940db4,source=volume,dest=volume,device=vdb,type=disk,shutdown=preserve \
--nic net-id=9b679a24-0084-4999-a72a-61a00483985e \
coreosfe-$(uuidgen)
